[package.build.backend]
channels = [
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package.build.config]
extra-input-globs = [
  "**/*.yaml",
  "**/*.rviz",
  "**/*.py",
  "**/*.srdf",
  "**/*.xacro",
  "**/*.urdf.xacro",
]

[package.host-dependencies]
ros2-distro-mutex = ">=0.14,<0.15"

[package.build-dependencies]
ros2-distro-mutex = ">=0.14,<0.15"

[package.run-dependencies]
ros2-distro-mutex = ">=0.14,<0.15"